// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/darenegade/SimpleGoaService/design
// --out=$(GOPATH)/src/github.com/darenegade/SimpleGoaService
// --version=v1.1.0-dirty
//
// API "HelloWorld": hello Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"bytes"
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// HelloHelloPayload is the hello hello action payload.
type HelloHelloPayload struct {
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}

// HelloHelloPath computes a request path to the hello action of hello.
func HelloHelloPath() string {

	return fmt.Sprintf("/hello")
}

// Say Hello to the service
func (c *Client) HelloHello(ctx context.Context, path string, payload *HelloHelloPayload, contentType string) (*http.Response, error) {
	req, err := c.NewHelloHelloRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewHelloHelloRequest create the request corresponding to the hello action endpoint of the hello resource.
func (c *Client) NewHelloHelloRequest(ctx context.Context, path string, payload *HelloHelloPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
