// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/darenegade/SimpleGoaService/design
// --out=$(GOPATH)/src/github.com/darenegade/SimpleGoaService
// --version=v1.1.0-dirty
//
// API "HelloWorld": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
