// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=SimpleGoaService/design
// --out=$(GOPATH)/src/SimpleGoaService
// --version=v1.1.0-dirty
//
// API "HelloWorld": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
